### ISSUE TITLE
Kneeboard for RedSands

### ISSUE THREAD

**Issue by thebgpikester** [Frosties82/RedSands#3]
Do a Kneeboard for the mission with MDC - Radio freqs, guides etc.

**Comment by Frosties82** [comment]
Are these updated and correct? 
You said something about them being incorrect a while ago?

**Comment by thebgpikester** [comment]
There's one minor issue. Stennis LSO is incorrect in the Kneeboard. You use the LSO from Airboss It's so minor im not sure it's worth the hassle.
![image](https://user-images.githubusercontent.com/22999891/52477528-18a5fc80-2b9a-11e9-8ac4-399971aa99a9.png)

**Comment by Frosties82** [comment]
Copy that, will close the issue.
