### ISSUE TITLE
Some slots are slotblocked even though they shouldnt be

### ISSUE THREAD

**Issue by Frosties82** [Frosties82/RedSands#32]
This has been observed at Stennis and Al Dhafra, both places shouldnt have any slotblockers at all.

Need to go through the slots and double-check it.

We can also remove the " -- " infront of some slots, since its not needed anymore (Drones are removed)

**Comment by Frosties82** [comment]
This is out of our hands it seems... 

Either for SSB or DCS to fix.. :

**Comment by thebgpikester** [comment]
So we discovered Global flag collisions between SSB and Airboss. Funky franky will be fixing in next or one after patch. FOr workaround, not sure, but it's livable for now or disable Airboss.

**Comment by Frosties82** [comment]
Airboss is disabled for the time being, but its just a commentrow so easily fixed when we have to re-activate.

**Comment by Frosties82** [comment]
Added the new Moose and tested it and the issue seems to have been fixed!

**Comment by Frosties82** [comment]
Fixed with the 11/2 MOOSE
