### ISSUE TITLE
Abu Musa Ground Forces routing adjustment

### ISSUE THREAD

**Issue by thebgpikester** [Frosties82/RedSands#34]
They seem to go right for the town. Stop them before they get stuck on a building!
(Avoid routing though building objects)

**Comment by Frosties82** [comment]
They are moved twice to NOT go thru the town. I think that we should make the capture zone smaller so the route is clear.,

**Comment by Frosties82** [comment]
Have adjusted the placement of the target zone and also changed the size a bit so they SHOULDNT want to go into town...
