### ISSUE TITLE
Ground Support Menu dissappearing..

### ISSUE THREAD

**Issue by Frosties82** [Frosties82/RedSands#35]
The menu for ground support is disappearing.
Need to investigate, or maybe re-write the script.

**Comment by Frosties82** [comment]
An scheduler is in the works to re-add the menus every X minutes if needed.

**Comment by thebgpikester** [comment]
FYI never had this issue or saw it. But DCS menus can do this kindda rubbish, it's a core game issue. Your solution will work fine ;)
