### ISSUE TITLE
Edit slots to have same WP's for consistency and user experience

### ISSUE THREAD

**Issue by thebgpikester** [Frosties82/RedSands#5]
In progress, going to have all clients that have programmable WP's to have the same logical WP list of all the islands, correct Bullseye, on correct places etc.

Also moving BE to logical place.

**Comment by Frosties82** [comment]
WP1: Bullseye
WP2: Sirri
WP3: Abu Musa
WP4: Kochak
WP5: Tunb
WP6: Bandar Lengeh
WP7: Kish
WP8: Bastak
WP9: Lar
WP10: Jahrom
WP11: Shiraz
WP12: Najafshahr
WP13: Kerman
WP14: Qeshm
WP15: Bandar Abbas

**Comment by Frosties82** [comment]
VIggen complete
