### ISSUE TITLE
IADS

### ISSUE THREAD

**Issue by thebgpikester** [Frosties82/RedSands#6]
Adding IADS will have two positive effects:

Sensor CPU use reduction (mission performance)
User experience - cleaner RWR and more scary radar popups

Suggest try Grimes IADS first with addByPrefix "AD-"

If not use moose scheduler and cycle through and random on/off.

**Comment by thebgpikester** [comment]
Basic on/off coded in dev via MOOSE.

**Comment by Frosties82** [comment]
IADS script are in place.
Right now the AO is pretty empty since HARM was implemented...
