### ISSUE TITLE
Red aircraft randomly 'pause'

### ISSUE THREAD

**Issue by 132Ashilta** [Frosties82/RedSands#7]
Aircraft sat on the taxiway at Al Minhad were stationary. I ploughed 80 cannon rounds into the side of one and the thing still lived.

Whilst dogfighting near Fujiarah or however you spell it, an F-14 drifted a full half a mile before pausing. It sat there forever.

**Comment by Frosties82** [comment]
Shooting aircrafts on the ground is a buggy issue, and is on EDs side, nothing we can do about that im afraid. 

The F-14 issue i really dont know how to check, but will keep my eyes open.

**Comment by 132Ashilta** [comment]
Would you like a Tacview/Screenshots of a paused F-14 in flight?

I appreciate it may be a game engine thing, but something, somewhere, is causing aircraft to pause and become invulnerable. I suspect this is a similar problem to that of the aircraft crashing into each other on the ground.

**Comment by Frosties82** [comment]
It sounds like a DCS issue tbh. We have nothing in place to "pause" aircrafts.
