### ISSUE TITLE
Helicopters and planes cannot reach 151.000 and only go up to 149.950.

### ISSUE THREAD

**Issue by Frosties82** [Frosties82/RedSands#9]

**Comment by Frosties82** [comment]
Examples are Mi8 and BlackShark so far. Would be much nicer if helicopters can use both channels for uniform and victor so they have awacs support from AI

**Comment by Frosties82** [comment]
Changing AWACS freqs to accomodate this.

AWACS E-3 : 131.000 MHz (Liwa)
AWACS E-2 : 131.500 MHz (Stennis)

**Comment by thebgpikester** [comment]
You need to update the briefing on this!

**Comment by Frosties82** [comment]
Fixed! Coming with the next MIZ push
